"""add attendance_status field

Revision ID: 8b1d64454b96
Revises: 25bb9e9f2f64
Create Date: 2026-02-18 10:11:24.645943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlalchemy_utc         #추가
import sqlmodel.sql.sqltypes  #추가
from sqlmodel import Text     #추가

# revision identifiers, used by Alembic.
revision: str = '8b1d64454b96'
down_revision: Union[str, Sequence[str], None] = '25bb9e9f2f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # attendance_status 컬럼 추가 (server_default 추가하여 기존 데이터 보호)
    op.add_column('bookings', sa.Column('attendance_status', sa.String(length=50), nullable=False, server_default='SCHEDULED'))

    # users 테이블 password -> hashed_password 변경
    op.add_column('users', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    # 기존 데이터가 있다면 복사 (현재는 데이터 없음)
    op.execute("UPDATE users SET hashed_password = password WHERE hashed_password IS NULL")
    # nullable=False로 변경
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password', nullable=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'hashed_password')
    op.drop_column('bookings', 'attendance_status')
    # ### end Alembic commands ###
